version: '1'

resources: &resources
  cpu: 100
  memory: 512
  essential: true
  linuxParameters:
    initProcessEnabled: true

services:
  worker:
    containerDefinitions:
      worker:
        <<: *resources
