version: '1'

resources: &resources
  cpu: 100
  memory: 512
  essential: true

services:
  worker:
    containerDefinitions:
      worker:
        <<: *resources
        command: "/usr/local/bin/gosu pganalyze /home/pganalyze/collector --statefile=/state/pganalyze-collector.state"
